---
version: '3.7'

services:
  apm-server:
    image: docker.elastic.co/apm/apm-server:7.17.0
    restart: unless-stopped
    mem_limit: 512M
    labels:
      co.elastic.logs/enabled: false
      co.elastic.metrics/raw: "[{\"module\":\"beat\",\"hosts\":\"apm-server:5066\",\"period\":\"10s\",\"xpack.enabled\":\"true\"}]"
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy
    cap_add: ["CHOWN", "DAC_OVERRIDE", "SETGID", "SETUID"]
    cap_drop: ["ALL"]
    ports:
      - 8200:8200
    command: >
      apm-server -e
        -E setup.kibana.enabled=true
        -E setup.kibana.host=http://kibana:5601
        -E setup.template.enabled=true
        -E setup.template.settings.index.number_of_replicas=0
        -E http.enabled=true
        -E http.host=0.0.0.0
        -E monitoring.enabled=false
        -E apm-server.rum.enabled=true
        -E apm-server.kibana.enabled=true
        -E apm-server.kibana.host=kibana:5601
        -E apm-server.kibana.username=elastic
        -E apm-server.kibana.password=$ELASTIC__INITIAL_PASSWORD
        -E output.elasticsearch.username=elastic
        -E output.elasticsearch.password=$ELASTIC__INITIAL_PASSWORD
        -E output.elasticsearch.hosts=["http://elasticsearch:9200"]
    container_name: apm
    networks:
      - oam
    healthcheck:
      interval: 10s
      retries: 12
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:5066/

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.0
    restart: unless-stopped
    mem_limit: 256M
    labels:
      co.elastic.logs/enabled: false
      co.elastic.metrics/raw: "[{\"module\":\"beat\",\"hosts\":\"filebeat:5066\",\"period\":\"10s\",\"xpack.enabled\":\"true\"}]"
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy
    user: root
    command: >
      filebeat -e
        -E setup.kibana.enabled=true
        -E setup.kibana.host=http://kibana:5601
        -E setup.template.enabled=true
        -E setup.template.settings.index.number_of_replicas=0
        -E http.enabled=true
        -E http.host=0.0.0.0
        -E monitoring.enabled=false
        -E output.elasticsearch.username=elastic
        -E output.elasticsearch.password=$ELASTIC__INITIAL_PASSWORD
        -E output.elasticsearch.hosts=["http://elasticsearch:9200"]
    volumes:
      - ./elastic/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $ELASTIC__LOG_FILES:/var/log/external:ro
    container_name: filebeat
    networks:
      - oam
    healthcheck:
      interval: 10s
      retries: 12
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:5066/

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:7.17.0
    restart: unless-stopped
    mem_limit: 256M
    labels:
      co.elastic.logs/enabled: false
      co.elastic.metrics/raw: "[{\"module\":\"beat\",\"hosts\":\"metricbeat:5066\",\"period\":\"10s\",\"xpack.enabled\":\"true\"}]"
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy
    user: root
    command: >
      metricbeat -e
        -E setup.kibana.enabled=true
        -E setup.kibana.host=http://kibana:5601
        -E setup.template.enabled=true
        -E setup.template.settings.index.number_of_replicas=0
        -E http.enabled=true
        -E http.host=0.0.0.0
        -E monitoring.enabled=false
        -E output.elasticsearch.username=elastic
        -E output.elasticsearch.password=$ELASTIC__INITIAL_PASSWORD
        -E output.elasticsearch.hosts=["http://elasticsearch:9200"]
    volumes:
      - ./elastic/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
      - ./elastic/metricbeat/system.yml:/usr/share/metricbeat/modules.d/system.yml
      - /var/run/docker.sock:/var/run/docker.sock:ro
    container_name: metricbeat
    networks:
      - oam
    healthcheck:
      interval: 10s
      retries: 12
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:5066/

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    restart: unless-stopped
    mem_limit: 5G
    labels:
      co.elastic.logs/enabled: true
      co.elastic.logs/module: elasticsearch
      co.elastic.logs/fileset: server
      co.elastic.metrics/raw: "[{\"module\":\"elasticsearch\",\"hosts\":\"http://elasticsearch:9200\",\"period\":\"10s\",\"xpack.enabled\":\"true\",\"username\":\"elastic\",\"password\":\"$ELASTIC__INITIAL_PASSWORD\"}]"
    environment:
      - cluster.name=datacenter
      - xpack.license.self_generated.type=trial
      - bootstrap.memory_lock=true
      - cluster.routing.allocation.disk.threshold_enabled=false
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.authc.api_key.enabled=true
      - xpack.monitoring.collection.enabled=true
      - xpack.monitoring.elasticsearch.collection.enabled=false
      - ELASTIC_PASSWORD=$ELASTIC__INITIAL_PASSWORD
      - ES_JAVA_OPTS=-XX:UseAVX=2 -Xms4g -Xmx4g
    ulimits:
      memlock:
        hard: -1
        soft: -1
    volumes:
      - ./elastic/elasticsearch/healthcheck.sh:/healthcheck.sh:ro
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    container_name: elasticsearch
    networks:
      - oam
    healthcheck:
      interval: 20s
      retries: 10
      test: /healthcheck.sh

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.0
    restart: unless-stopped
    mem_limit: 1G
    labels:
      co.elastic.logs/enabled: false
      co.elastic.logs/module: kibana
      co.elastic.logs/fileset: log
      co.elastic.metrics/raw: "[{\"module\":\"kibana\",\"hosts\":\"http://kibana:5601\",\"period\":\"10s\",\"xpack.enabled\":\"true\",\"username\":\"kibana_system\",\"password\":\"$ELASTIC__INITIAL_PASSWORD\"}]"
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      ELASTICSEARCH_USERNAME: kibana_system
      ELASTICSEARCH_PASSWORD: $ELASTIC__INITIAL_PASSWORD
      MONITORING_KIBANA_COLLECTION_ENABLED: false
      XPACK_APM_AUTOCREATEAPMINDEXPATTERN: true
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: $ELASTIC__ENCRYPTION_KEY
      XPACK_SECURITY_ENCRYPTIONKEY: $ELASTIC__ENCRYPTION_KEY
      XPACK_REPORTING_ENCRYPTIONKEY: $ELASTIC__ENCRYPTION_KEY
    ports:
      - 5601:5601
    container_name: kibana
    networks:
      - oam
    healthcheck:
      interval: 10s
      retries: 20
      test: curl -u kibana_system:$$ELASTICSEARCH_PASSWORD --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:5601/api/status

networks:
  oam:

volumes:
  esdata:
    driver: local
