---
version: '3.7'

services:
  setup:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC__STACK_VERSION}
    command: >
      bash -c '
        echo "Waiting for Elasticsearch availability";
        until curl -s -u elastic:${ELASTIC__INITIAL_PASSWORD} http://elasticsearch:9200/_cluster/health | grep -vq '"status":"red"'; do sleep 30; done;
        echo "Setting kibana_system password";
        until curl -s -X POST -u elastic:${ELASTIC__INITIAL_PASSWORD} -H "Content-Type: application/json" http://elasticsearch:9200/_security/user/kibana_system/_password -d "{\"password\":\"${ELASTIC__INITIAL_PASSWORD}\"}" | grep -q "^{}"; do sleep 10; done;
        echo "All done!";
      '
    container_name: elastic_setup
    volumes:
      - setup:/usr/share/setup
    networks:
      - oam

  fleet-server-apm:
    image: docker.elastic.co/beats/elastic-agent:${ELASTIC__STACK_VERSION}
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy
    restart: unless-stopped
    mem_limit: 512M
    environment:
      FLEET_SERVER_ENABLE: "1"
      FLEET_SERVER_POLICY_ID: fleet-server-apm
      FLEET_SERVER_ELASTICSEARCH_HOST: http://elasticsearch:9200
      FLEET_SERVER_ELASTICSEARCH_USERNAME: elastic
      FLEET_SERVER_ELASTICSEARCH_PASSWORD: $ELASTIC__INITIAL_PASSWORD
      FLEET_SERVER_INSECURE_HTTP: "true"
      FLEET_URL: https://fleet-server:8220
      KIBANA_FLEET_SETUP: "true"
      KIBANA_HOST: http://kibana:5601
      KIBANA_USERNAME: elastic
      KIBANA_PASSWORD: $ELASTIC__INITIAL_PASSWORD
    container_name: fleet-server
    ports:
      - 8220:8220
      - 8200:8200
    networks:
      - oam
    healthcheck:
      interval: 10s
      retries: 12
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:8220/api/status && curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:8200

  filebeat:
    image: docker.elastic.co/beats/filebeat:${ELASTIC__STACK_VERSION}
    restart: unless-stopped
    mem_limit: 256M
    labels:
      co.elastic.logs/enabled: false
      co.elastic.metrics/raw: "[{\"module\":\"beat\",\"hosts\":\"filebeat:5066\",\"period\":\"10s\",\"xpack.enabled\":\"true\"}]"
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy
    user: root
    command: >
      filebeat -e
        -E setup.kibana.enabled=true
        -E setup.kibana.host=http://kibana:5601
        -E setup.template.enabled=true
        -E setup.template.settings.index.number_of_replicas=0
        -E http.enabled=true
        -E http.host=0.0.0.0
        -E monitoring.enabled=false
        -E output.elasticsearch.username=elastic
        -E output.elasticsearch.password=$ELASTIC__INITIAL_PASSWORD
        -E output.elasticsearch.hosts=["http://elasticsearch:9200"]
    volumes:
      - ./elastic/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $ELASTIC__LOG_FILES:/var/log/external:ro
    container_name: filebeat
    networks:
      - oam
    healthcheck:
      interval: 10s
      retries: 12
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:5066/

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:${ELASTIC__STACK_VERSION}
    restart: unless-stopped
    mem_limit: 256M
    labels:
      co.elastic.logs/enabled: false
      co.elastic.metrics/raw: "[{\"module\":\"beat\",\"hosts\":\"metricbeat:5066\",\"period\":\"10s\",\"xpack.enabled\":\"true\"}]"
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy
    user: root
    command: >
      metricbeat -e
        -E setup.kibana.enabled=true
        -E setup.kibana.host=http://kibana:5601
        -E setup.template.enabled=true
        -E setup.template.settings.index.number_of_replicas=0
        -E http.enabled=true
        -E http.host=0.0.0.0
        -E monitoring.enabled=false
        -E output.elasticsearch.username=elastic
        -E output.elasticsearch.password=$ELASTIC__INITIAL_PASSWORD
        -E output.elasticsearch.hosts=["http://elasticsearch:9200"]
    volumes:
      - ./elastic/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
      - ./elastic/metricbeat/system.yml:/usr/share/metricbeat/modules.d/system.yml
      - /var/run/docker.sock:/var/run/docker.sock:ro
    container_name: metricbeat
    networks:
      - oam
    healthcheck:
      interval: 10s
      retries: 12
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:5066/

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC__STACK_VERSION}
    restart: unless-stopped
    mem_limit: 5G
    labels:
      co.elastic.logs/enabled: true
      co.elastic.logs/module: elasticsearch
      co.elastic.logs/fileset: server
      co.elastic.metrics/raw: "[{\"module\":\"elasticsearch\",\"hosts\":\"http://elasticsearch:9200\",\"period\":\"10s\",\"xpack.enabled\":\"true\",\"username\":\"elastic\",\"password\":\"$ELASTIC__INITIAL_PASSWORD\"}]"
    depends_on:
      setup:
        condition: service_started
    environment:
      - cluster.name=datacenter
      - xpack.license.self_generated.type=trial
      - bootstrap.memory_lock=true
      - cluster.routing.allocation.disk.threshold_enabled=false
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.authc.api_key.enabled=true
      - xpack.monitoring.collection.enabled=true
      - xpack.monitoring.elasticsearch.collection.enabled=false
      - ELASTIC_PASSWORD=$ELASTIC__INITIAL_PASSWORD
      - ES_JAVA_OPTS=-Xms4g -Xmx4g
    ulimits:
      memlock:
        hard: -1
        soft: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    container_name: elasticsearch
    networks:
      - oam
    healthcheck:
      test: curl -u elastic:$$ELASTIC_PASSWORD -s http://localhost:9200/_cluster/health | grep -vq '"status":"red"'
      interval: 20s
      retries: 10

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELASTIC__STACK_VERSION}
    restart: unless-stopped
    mem_limit: 1G
    labels:
      co.elastic.logs/enabled: false
      co.elastic.logs/module: kibana
      co.elastic.logs/fileset: log
      co.elastic.metrics/raw: "[{\"module\":\"kibana\",\"hosts\":\"http://kibana:5601\",\"period\":\"10s\",\"xpack.enabled\":\"true\",\"username\":\"kibana_system\",\"password\":\"$ELASTIC__INITIAL_PASSWORD\"}]"
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      ELASTICSEARCH_USERNAME: kibana_system
      ELASTICSEARCH_PASSWORD: $ELASTIC__INITIAL_PASSWORD
      MONITORING_KIBANA_COLLECTION_ENABLED: false
      XPACK_APM_AUTOCREATEAPMINDEXPATTERN: true
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: $ELASTIC__ENCRYPTION_KEY
      XPACK_SECURITY_ENCRYPTIONKEY: $ELASTIC__ENCRYPTION_KEY
      XPACK_REPORTING_ENCRYPTIONKEY: $ELASTIC__ENCRYPTION_KEY
      XPACK_FLEET_AGENTS_FLEET_SERVER_HOSTS: '["https://fleet-server:8220"]'
      XPACK_FLEET_AGENTS_ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    volumes:
      - ./elastic/kibana.yml:/usr/share/kibana/config/kibana.yml
      - kibanadata:/usr/share/kibana/data
    ports:
      - 5601:5601
    container_name: kibana
    networks:
      - oam
    healthcheck:
      interval: 10s
      retries: 20
      test: curl -u kibana_system:$$ELASTICSEARCH_PASSWORD --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:5601/api/status

networks:
  oam:

volumes:
  setup:
    driver: local
  esdata:
    driver: local
  kibanadata:
    driver: local
