receivers:
  otlp:
    protocols:
      grpc:

processors:

exporters:
  prometheusremotewrite:
    endpoint: http://prometheus:9090/api/v1/write
    resource_to_telemetry_conversion:
      enabled: true
    target_info:
      enabled: true
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
  logging:
    loglevel: debug

extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [otlp/tempo]
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [prometheusremotewrite]
    logs:
      receivers: [otlp]
      processors: []
      exporters: [loki]
