apiVersion: 1

datasources:
- name: Loki
  type: loki
  uid: loki
  access: proxy
  orgId: 1
  url: http://loki:3100
  jsonData:
     tlsAuth: false
     tlsAuthWithCACert: false
     manageAlerts: false
     derivedFields:
      - datasourceUid: tempo
        matcherRegex: (\w{32})
        url: '$${__value.raw}'
        name: TraceID     
  version: 1
  editable: false
