apiVersion: 1

datasources:
- name: Tempo
  type: tempo
  uid: tempo
  access: proxy
  orgId: 1
  url: http://tempo:3100
  jsonData:
    tlsAuth: false
    tlsAuthWithCACert: false
    manageAlerts: false
    tracesToLogs:
      datasourceUid: loki
  version: 1
  editable: false
